name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t akshaylilac/complex-client ./client
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t akshaylilac/complex-server ./server
  build-worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t akshaylilac/complex-worker ./worker

  build-nginx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t akshaylilac/complex-nginx ./nginx

  push-client:
    runs-on: ubuntu-latest
    needs: [build-client]
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run: docker push akshaylilac/complex-client
  push-server:
    runs-on: ubuntu-latest
    needs: [build-server]
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run: docker push akshaylilac/complex-server
  push-worker:
    runs-on: ubuntu-latest
    needs: [build-worker]
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run: docker push akshaylilac/complex-worker
  push-nginx:
    runs-on: ubuntu-latest
    needs: [build-nginx]
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run: docker push akshaylilac/complex-nginx
