name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
            docker build -t akshaylilac/complex-client ./client
            docker build -t akshaylilac/complex-server ./server
            docker build -t akshaylilac/complex-worker ./worker
            docker build -t akshaylilac/complex-nginx ./nginx

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run:  |
             docker push akshaylilac/complex-client

