name: Docker-Build-Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-push-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t akshaylilac/complex-client --tag akshaylilac/complex-client:$(date +%s) ./client
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run: docker push akshaylilac/complex-client

  build-push-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t akshaylilac/complex-server ./server
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run: docker push akshaylilac/complex-server

  build-push-worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t akshaylilac/complex-worker ./worker
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run: docker push akshaylilac/complex-worker

  build-push-nginx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t akshaylilac/complex-nginx ./nginx
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - uses: actions/checkout@v2
    - name: Checkout
      run: docker push akshaylilac/complex-nginx


  docker-deploy:
    needs: [build-push-client, build-push-server, build-push-worker, build-push-nginx]
    name: Deploy Docker to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AWS_SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: rsync over ssh
      run: docker-compose up -d



